
export const AUTH_ENABLE_LOADER = 'AUTH_ENABLE_LOADER';
export const AUTH_DISABLE_LOADER = 'AUTH_DISABLE_LOADER';

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILED = 'GET_TOKEN_FAILED';
