export const GRID_ENABLE_LOADER = 'GRID_ENABLE_LOADER';
export const GRID_DISABLE_LOADER = 'GRID_DISABLE_LOADER';

export const GET_IMAGE_LIST_REQUEST = 'GET_IMAGE_LIST_REQUEST';
export const GET_IMAGE_LIST_SUCCESS = 'GET_IMAGE_LIST_SUCCESS';
export const GET_IMAGE_LIST_FAILED = 'GET_IMAGE_LIST_FAILED';
