export const GET_IMAGE_DETAILS_REQUEST = 'GET_IMAGE_DETAILS_REQUEST';
export const GET_IMAGE_DETAILS_SUCCESS = 'GET_IMAGE_DETAILS_SUCCESS';
export const GET_IMAGE_DETAILS_FAILED = 'GET_IMAGE_DETAILS_FAILED';
export const IMAGE_DETAILS_ENABLE_LOADER = 'IMAGE_DETAILS_ENABLE_LOADER';
export const IMAGE_DETAILS_DISABLE_LOADER = 'IMAGE_DETAILS_DISABLE_LOADER';
